#!/bin/bash
# split sorted keywords
# RUN THIS SCRIPT IN CURRENT DIRECTORY

cd "$( dirname "${BASH_SOURCE[0]}" )" 

rm -f 10000-sorted-*.txt

echo -e 'AUTO GENERATED BY SCRIPT.\nDO NOT EDIT THIS DIRECTORY' > README.txt

mysql -h 192.168.3.175 -uroot -proot keyword < 10000keywords.sql | tail -n +2  > 10000-sorted-all.txt

sum_1=`wc -l < 10000-sorted-all.txt`
avg_1=$((sum_1/10+1))
csplit -k -f 10000-sorted- -b %02d.txt 10000-sorted-all.txt $avg_1 {*}
